// Mocks generated by Mockito 5.4.6 from annotations
// in atomberg/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:atomberg/src/core/api_service.dart' as _i3;
import 'package:atomberg/src/features/dashboard/domain/device_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDevice_0 extends _i1.SmartFake implements _i2.Device {
  _FakeDevice_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Device>> getDevices() =>
      (super.noSuchMethod(
            Invocation.method(#getDevices, []),
            returnValue: _i4.Future<List<_i2.Device>>.value(<_i2.Device>[]),
          )
          as _i4.Future<List<_i2.Device>>);

  @override
  _i4.Future<void> sendCommand(
    String? deviceId,
    Map<String, dynamic>? command,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendCommand, [deviceId, command]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Device> getDeviceState(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceState, [deviceId]),
            returnValue: _i4.Future<_i2.Device>.value(
              _FakeDevice_0(
                this,
                Invocation.method(#getDeviceState, [deviceId]),
              ),
            ),
          )
          as _i4.Future<_i2.Device>);
}
